"""Reviewed additions for cohort 2026.10.0.

These records do not edit cohort 2026.09.0. New people stay `needs_review`.
Automated profile links stay `machine_validated` or `needs_review`. Nothing
here is `human_verified`.
"""

from __future__ import annotations

VERIFIED_AT = "2026-10-04T21:00:00Z"
BASE_SHA = "d13c8ab9bc2d643e28b7f52daf1a4c15724e77d7"
BASE_VERSION = "2026.09.0"
COHORT_VERSION = "2026.10.0"
COHORT_ID = "cohort_2026_10"

NEW_ORGANIZATIONS = [
    {
        "id": "org:lawzero",
        "slug": "lawzero",
        "name": "LawZero",
        "organization_type": "safety_org",
        "canonical_url": "https://lawzero.org/en",
        "country_code": None,
        "country_note": "The public page says LawZero was incubated at Mila in Quebec and mentions joint Canada-Germany funding. It does not state a single headquarters country, so country_code stays null.",
    },
    {
        "id": "org:naver-cloud",
        "slug": "naver-cloud",
        "name": "NAVER Cloud",
        "organization_type": "frontier_lab",
        "canonical_url": "https://www.navercorp.com/en/tech/hyperclovax",
        "country_code": "KR",
        "country_note": "Organization headquarters country for NAVER, the publisher of the HyperCLOVA X pages. It is not the nationality of the people affiliated with it.",
    },
]

NEW_PEOPLE = [
    {
        "slug": "neil-zeghidour",
        "display_name": "Neil Zeghidour",
        "given_name": "Neil",
        "family_name": "Zeghidour",
        "name_variants": [],
        "name_distinctiveness": "high",
        "inclusion_reason": "frontier_model_author",
        "inclusion_reasons": ["frontier_model_author", "frontier_lab_researcher"],
        "focus": "frontier_lab",
        "status": "review",
        "institution_keywords": ["Kyutai"],
        "bio_short": "Named on the Kyutai team page and as an equal-contribution author of the Moshi speech-text foundation model on Kyutai's papers page.",
        "inclusion_evidence": [
            "https://kyutai.org/team/",
            "https://kyutai.org/papers/",
        ],
        "affiliations": [
            {"organization_slug": "kyutai", "role": "Researcher", "basis": "current", "confidence": "medium"},
        ],
    },
    {
        "slug": "alexandre-defossez",
        "display_name": "Alexandre Défossez",
        "given_name": "Alexandre",
        "family_name": "Défossez",
        "name_variants": ["Alexandre Defossez"],
        "name_distinctiveness": "high",
        "inclusion_reason": "frontier_model_author",
        "inclusion_reasons": ["frontier_model_author", "frontier_lab_researcher"],
        "focus": "frontier_lab",
        "status": "review",
        "institution_keywords": ["Kyutai"],
        "bio_short": "Named on the Kyutai team page and as an equal-contribution author of Moshi. The Moshi paper lists alex@kyutai.org.",
        "inclusion_evidence": [
            "https://kyutai.org/team/",
            "https://kyutai.org/papers/",
        ],
        "affiliations": [
            {"organization_slug": "kyutai", "role": "Researcher", "basis": "current", "confidence": "medium"},
        ],
    },
    {
        "slug": "yan-junjie",
        "display_name": "Yan Junjie",
        "given_name": "Junjie",
        "family_name": "Yan",
        "name_variants": ["闫俊杰"],
        "name_distinctiveness": "low",
        "inclusion_reason": "frontier_lab_researcher",
        "inclusion_reasons": ["frontier_lab_researcher"],
        "focus": "frontier_lab",
        "status": "review",
        "institution_keywords": ["MiniMax"],
        "bio_short": "MiniMax founder, chairman, CEO, and CTO on the company's investor-relations management page. The page says he sets strategy particularly for AI research and development. No OpenAlex id is attached, because the name is not distinctive.",
        "inclusion_evidence": [
            "https://ir.minimax.cn/en/corporate-information/management",
            "https://ir.minimax.cn/corporate-information/management",
        ],
        "affiliations": [
            {
                "organization_slug": "minimax",
                "role": "Founder, Chairman, CEO and CTO",
                "basis": "current",
                "confidence": "high",
            }
        ],
    },
    {
        "slug": "sung-nako",
        "display_name": "Sung Nako",
        "given_name": "Nako",
        "family_name": "Sung",
        "name_variants": ["Nako Sung"],
        "name_distinctiveness": "low",
        "inclusion_reason": "frontier_lab_researcher",
        "inclusion_reasons": ["frontier_lab_researcher"],
        "focus": "frontier_lab",
        "status": "review",
        "institution_keywords": ["NAVER", "HyperCLOVA"],
        "bio_short": "Named on an official NAVER press release as Executive Director of Hyperscale AI at NAVER Cloud, the group building HyperCLOVA X. Role confidence is medium because the title comes from a press release rather than a staff directory.",
        "inclusion_evidence": ["https://www.navercorp.com/en/media/pressReleasesDetail?seq=33066"],
        "affiliations": [
            {
                "organization_slug": "naver-cloud",
                "role": "Executive Director of Hyperscale AI",
                "basis": "current",
                "confidence": "medium",
            }
        ],
    },
    {
        "slug": "yoo-kang-min",
        "display_name": "Yoo Kang-min",
        "given_name": "Kang-min",
        "family_name": "Yoo",
        "name_variants": ["Kang-min Yoo"],
        "name_distinctiveness": "low",
        "inclusion_reason": "frontier_lab_researcher",
        "inclusion_reasons": ["frontier_lab_researcher"],
        "focus": "frontier_lab",
        "status": "review",
        "institution_keywords": ["NAVER", "HyperCLOVA"],
        "bio_short": "Named on an official NAVER press release as Leader of Foundation Research at NAVER Cloud for HyperCLOVA X THINK. The romanization follows that English release. No Korean-script name is copied from a secondary profile.",
        "inclusion_evidence": ["https://www.navercorp.com/en/media/pressReleasesDetail?seq=33066"],
        "affiliations": [
            {
                "organization_slug": "naver-cloud",
                "role": "Leader of Foundation Research",
                "basis": "current",
                "confidence": "medium",
            }
        ],
    },
]

ADDITIONAL_AFFILIATIONS = [
    {
        "person_slug": "yoshua-bengio",
        "organization_slug": "lawzero",
        "role": "Leads LawZero research",
        "basis": "relevant",
        "confidence": "high",
        "verification_method": "institutional_profile",
        "review_state": "needs_review",
        "evidence_url": "https://lawzero.org/en",
        "note": "The LawZero page says its research is led by Yoshua Bengio. His current Mila affiliation is unchanged. This row does not replace it.",
    }
]

PLATFORM_PROFILES = [
    {
        "person_slug": "eliezer-yudkowsky",
        "namespace": "forum_magnum",
        "site": "lesswrong",
        "external_id": "nmk3nLpQE89dMRzzN",
        "handle": "eliezer_yudkowsky",
        "profile_names": ["Eliezer Yudkowsky"],
        "canonical_url": "https://www.lesswrong.com/users/eliezer_yudkowsky",
        "linked_from_owned_source": True,
        "evidence_url": "https://www.lesswrong.com/posts/uMQ3cqWDPHhjtiesc/agi-ruin-a-list-of-lethalities",
        "confidence": "high",
        "review_state": "machine_validated",
    },
    {
        "person_slug": "paul-christiano",
        "namespace": "forum_magnum",
        "site": "lesswrong",
        "external_id": "gb44edJjXhte8DA3A",
        "handle": "paulfchristiano",
        "profile_names": ["Paul Christiano"],
        "canonical_url": "https://www.lesswrong.com/users/paulfchristiano",
        "linked_from_owned_source": True,
        "evidence_url": "https://www.lesswrong.com/posts/xWMqsvHapP3nwdSW8/my-views-on-doom",
        "confidence": "high",
        "review_state": "machine_validated",
        "note": "The handle paulfchristiano does not match the name key. The account is accepted because the fullName field is Paul Christiano and the post was already linked to him.",
    },
    {
        "person_slug": "andrew-critch",
        "namespace": "forum_magnum",
        "site": "lesswrong",
        "external_id": "f7Mag7bDZKv59Bsaw",
        "handle": "andrew_critch",
        "profile_names": ["Andrew Critch"],
        "canonical_url": "https://www.lesswrong.com/users/andrew_critch",
        "linked_from_owned_source": True,
        "evidence_url": "https://www.lesswrong.com/posts/LpM3EAakwYdS6aRKf/what-multipolar-failure-looks-like-and-robust-agent-agnostic",
        "confidence": "high",
        "review_state": "machine_validated",
    },
    {
        "person_slug": "ajeya-cotra",
        "namespace": "forum_magnum",
        "site": "lesswrong",
        "external_id": "BpJX4jYXD836kDJ8e",
        "handle": "ajeya-cotra",
        "profile_names": ["Ajeya Cotra"],
        "canonical_url": "https://www.lesswrong.com/users/ajeya-cotra",
        "linked_from_owned_source": True,
        "evidence_url": "https://www.lesswrong.com/posts/AfH2oPHCApdKicM4m/two-year-update-on-my-personal-ai-timelines",
        "confidence": "high",
        "review_state": "machine_validated",
    },
    {
        "person_slug": "yoshua-bengio",
        "namespace": "bluesky",
        "site": "bluesky",
        "external_id": "did:plc:3ezp6hkpykqzyexh2kzjybij",
        "handle": "yoshuabengio.bsky.social",
        "profile_names": ["Yoshua Bengio"],
        "canonical_url": "https://bsky.app/profile/yoshuabengio.bsky.social",
        "linked_from_owned_source": True,
        "evidence_url": "https://yoshuabengio.org/en",
        "confidence": "high",
        "review_state": "machine_validated",
    },
    {
        "person_slug": "nathan-lambert",
        "namespace": "bluesky",
        "site": "bluesky",
        "external_id": "did:plc:brkj2yocng7vtggmyujy4khq",
        "handle": "natolambert.bsky.social",
        "profile_names": ["Nathan Lambert"],
        "canonical_url": "https://bsky.app/profile/natolambert.bsky.social",
        "linked_from_owned_source": True,
        "evidence_url": "https://www.interconnects.ai/",
        "confidence": "high",
        "review_state": "machine_validated",
    },
]

IDENTITY_REJECTIONS = [
    {
        "kind": "alias_not_exact_name",
        "person_id": "person:joseph-carlsmith",
        "namespace": "forum_magnum",
        "handle": "joe-carlsmith",
        "profile_names": ["Joe Carlsmith"],
        "canonical_url": "https://www.lesswrong.com/users/joe-carlsmith",
        "reason": "Joe Carlsmith and Joseph Carlsmith do not share a name key. An earlier lead associated the post byline with Joseph Carlsmith. This version does not attach the account.",
        "cohort_version": COHORT_VERSION,
    },
    {
        "kind": "no_corroborating_link",
        "person_id": "person:nate-soares",
        "namespace": "forum_magnum",
        "handle": "so8res",
        "profile_names": ["Nate Soares"],
        "canonical_url": "https://www.lesswrong.com/users/so8res",
        "reason": "The LessWrong fullName is Nate Soares, and the slug was seen as a coauthor on an Eliezer Yudkowsky post. The slug itself is not his name, and no page already linked to Nate Soares points at this account. The account is not attached.",
        "cohort_version": COHORT_VERSION,
    },
    {
        "kind": "institution_account",
        "namespace": "bluesky",
        "external_id": "did:plc:3bwecryzndblwdqgknuwjzh4",
        "handle": "mila-quebec.bsky.social",
        "profile_names": ["Mila - Institut québécois d'IA"],
        "canonical_url": "https://bsky.app/profile/mila-quebec.bsky.social",
        "linked_from": "https://yoshuabengio.org/en",
        "reason": "Yoshua Bengio's site links this organization account next to his personal account. The display name is Mila, not Yoshua Bengio. It is not merged into him.",
        "cohort_version": COHORT_VERSION,
    },
]

NEW_IDENTITIES = [
    {
        "person_slug": "hannaneh-hajishirzi",
        "namespace": "semantic_scholar",
        "external_id": "2548384",
        "canonical_url": "https://www.semanticscholar.org/author/Hannaneh-Hajishirzi/2548384",
        "handle": None,
        "verification_method": "personal_site_profile_link",
        "confidence": "high",
        "review_state": "machine_validated",
        "evidence": {
            "page_url": "https://hannaneh.ai/",
            "reached_from": "https://homes.cs.washington.edu/~hannaneh",
            "note": "The registered university page redirects to hannaneh.ai, and that page links this Semantic Scholar author URL.",
        },
    },
    {
        "person_slug": "yoshua-bengio",
        "namespace": "bluesky",
        "external_id": "did:plc:3ezp6hkpykqzyexh2kzjybij",
        "canonical_url": "https://bsky.app/profile/yoshuabengio.bsky.social",
        "handle": "yoshuabengio.bsky.social",
        "verification_method": "bluesky_profile_name_and_site_link",
        "confidence": "high",
        "review_state": "machine_validated",
        "evidence": {"page_url": "https://yoshuabengio.org/en", "display_name": "Yoshua Bengio"},
    },
    {
        "person_slug": "nathan-lambert",
        "namespace": "bluesky",
        "external_id": "did:plc:brkj2yocng7vtggmyujy4khq",
        "canonical_url": "https://bsky.app/profile/natolambert.bsky.social",
        "handle": "natolambert.bsky.social",
        "verification_method": "bluesky_profile_name_and_site_link",
        "confidence": "high",
        "review_state": "machine_validated",
        "evidence": {"page_url": "https://www.interconnects.ai/", "display_name": "Nathan Lambert"},
    },
]

NEW_SOURCES = [
    {
        "person_slug": "eliezer-yudkowsky",
        "id_suffix": "blog:lesswrong",
        "source_type": "blog",
        "name": "Eliezer Yudkowsky on LessWrong",
        "canonical_url": "https://www.lesswrong.com/users/eliezer_yudkowsky",
        "platform": "lesswrong",
        "collection_method": "forum_magnum_api",
        "site": "lesswrong",
        "user_id": "nmk3nLpQE89dMRzzN",
        "expected_slug": "eliezer_yudkowsky",
        "enabled": True,
        "continuously_collectible": True,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "forum_author_on_linked_post",
        "rights_notes": "LessWrong public GraphQL. Store the author field, canonical URL, time, and a short excerpt. Do not store the full post.",
        "language": None,
    },
    {
        "person_slug": "paul-christiano",
        "id_suffix": "blog:lesswrong",
        "source_type": "blog",
        "name": "Paul Christiano on LessWrong",
        "canonical_url": "https://www.lesswrong.com/users/paulfchristiano",
        "platform": "lesswrong",
        "collection_method": "forum_magnum_api",
        "site": "lesswrong",
        "user_id": "gb44edJjXhte8DA3A",
        "expected_slug": "paulfchristiano",
        "enabled": True,
        "continuously_collectible": True,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "forum_author_on_linked_post",
        "rights_notes": "LessWrong public GraphQL. Store the author field, canonical URL, time, and a short excerpt. Do not store the full post.",
        "language": None,
    },
    {
        "person_slug": "andrew-critch",
        "id_suffix": "blog:lesswrong",
        "source_type": "blog",
        "name": "Andrew Critch on LessWrong",
        "canonical_url": "https://www.lesswrong.com/users/andrew_critch",
        "platform": "lesswrong",
        "collection_method": "forum_magnum_api",
        "site": "lesswrong",
        "user_id": "f7Mag7bDZKv59Bsaw",
        "expected_slug": "andrew_critch",
        "enabled": True,
        "continuously_collectible": True,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "forum_author_on_linked_post",
        "rights_notes": "LessWrong public GraphQL. Store the author field, canonical URL, time, and a short excerpt. Do not store the full post.",
        "language": None,
    },
    {
        "person_slug": "ajeya-cotra",
        "id_suffix": "blog:lesswrong",
        "source_type": "blog",
        "name": "Ajeya Cotra on LessWrong",
        "canonical_url": "https://www.lesswrong.com/users/ajeya-cotra",
        "platform": "lesswrong",
        "collection_method": "forum_magnum_api",
        "site": "lesswrong",
        "user_id": "BpJX4jYXD836kDJ8e",
        "expected_slug": "ajeya-cotra",
        "enabled": True,
        "continuously_collectible": True,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "forum_author_on_linked_post",
        "rights_notes": "LessWrong public GraphQL. Store the author field, canonical URL, time, and a short excerpt. Do not store the full post.",
        "language": None,
    },
    {
        "person_slug": "yoshua-bengio",
        "id_suffix": "bluesky",
        "source_type": "bluesky",
        "name": "Yoshua Bengio on Bluesky",
        "canonical_url": "https://bsky.app/profile/yoshuabengio.bsky.social",
        "platform": "bluesky",
        "collection_method": "bluesky_api",
        "actor": "yoshuabengio.bsky.social",
        "enabled": True,
        "continuously_collectible": True,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "bluesky_profile_name_and_site_link",
        "rights_notes": "Public Bluesky AppView author feed. Reposts are dropped. Original-language text is kept. Translations are not invented.",
        "language": None,
    },
    {
        "person_slug": "nathan-lambert",
        "id_suffix": "bluesky",
        "source_type": "bluesky",
        "name": "Nathan Lambert on Bluesky",
        "canonical_url": "https://bsky.app/profile/natolambert.bsky.social",
        "platform": "bluesky",
        "collection_method": "bluesky_api",
        "actor": "natolambert.bsky.social",
        "enabled": True,
        "continuously_collectible": True,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "bluesky_profile_name_and_site_link",
        "rights_notes": "Public Bluesky AppView author feed. Reposts are dropped. The account is the person, not an organization.",
        "language": None,
    },
    {
        "person_slug": "hannaneh-hajishirzi",
        "id_suffix": "personal_website:hannaneh-ai",
        "source_type": "personal_website",
        "name": "Hannaneh Hajishirzi personal site",
        "canonical_url": "https://hannaneh.ai/",
        "platform": "personal_website",
        "collection_method": "reference_only",
        "enabled": False,
        "continuously_collectible": False,
        "runner_wired": False,
        "review_state": "machine_validated",
        "verification_method": "personal_site_profile_link",
        "rights_notes": "Confirmed personal site reached by redirect from the registered university page. Page text is not stored.",
        "language": "en",
    },
    {
        "person_slug": "yan-junjie",
        "id_suffix": "lab_page:minimax-ir",
        "source_type": "lab_page",
        "name": "MiniMax management biography",
        "canonical_url": "https://ir.minimax.cn/corporate-information/management",
        "platform": "lab_page",
        "collection_method": "reference_only",
        "enabled": False,
        "continuously_collectible": False,
        "runner_wired": False,
        "review_state": "needs_review",
        "verification_method": "institutional_profile",
        "rights_notes": "Chinese-language institutional biography. It is not a personal statement and it is not continuously collected.",
        "language": "zh",
        "claim_level": "institution",
    },
    {
        "person_slug": "sung-nako",
        "id_suffix": "press:hyperclova-think",
        "source_type": "press",
        "name": "NAVER HyperCLOVA X THINK announcement",
        "canonical_url": "https://www.navercorp.com/en/media/pressReleasesDetail?seq=33066",
        "platform": "press",
        "collection_method": "reference_only",
        "enabled": False,
        "continuously_collectible": False,
        "runner_wired": False,
        "review_state": "needs_review",
        "verification_method": "institutional_profile",
        "rights_notes": "Official English press release. The excerpt is a direct quote. The rest of the document is an institutional announcement. A Korean original was not collected.",
        "language": "en",
        "claim_level": "quoted_in_institutional_release",
    },
    {
        "person_slug": "yoo-kang-min",
        "id_suffix": "press:hyperclova-think",
        "source_type": "press",
        "name": "NAVER HyperCLOVA X THINK announcement",
        "canonical_url": "https://www.navercorp.com/en/media/pressReleasesDetail?seq=33066",
        "platform": "press",
        "collection_method": "reference_only",
        "enabled": False,
        "continuously_collectible": False,
        "runner_wired": False,
        "review_state": "needs_review",
        "verification_method": "institutional_profile",
        "rights_notes": "Official English press release. The excerpt is a direct quote. The rest of the document is an institutional announcement. A Korean original was not collected.",
        "language": "en",
        "claim_level": "quoted_in_institutional_release",
    },
]

PRESS_EXCERPTS = [
    {
        "person_slug": "sung-nako",
        "display_name": "Sung Nako",
        "canonical_url": "https://www.navercorp.com/en/media/pressReleasesDetail?seq=33066",
        "published_at": "2025-06-30T00:00:00Z",
        "language": "en",
        "translation": None,
        "translation_note": "Official English release. Korean original not collected. This text is not labeled as a translation produced by this pipeline.",
        "text": "We are evolving HyperCLOVA X along two major axes—‘enhancement of intelligence’ and ‘expansion of perception’—and with HyperCLOVA X THINK, we’ve achieved substantial progress in terms of intelligence.",
        "claim_level": "quoted_in_institutional_release",
        "role": "speaker",
    },
    {
        "person_slug": "yoo-kang-min",
        "display_name": "Yoo Kang-min",
        "canonical_url": "https://www.navercorp.com/en/media/pressReleasesDetail?seq=33066",
        "published_at": "2025-06-30T00:00:00Z",
        "language": "en",
        "translation": None,
        "translation_note": "Official English release. Korean original not collected. This text is not labeled as a translation produced by this pipeline.",
        "text": "Although this reasoning model was not specifically designed for multimodal reasoning, it still demonstrated notable performance in visual reasoning tasks.",
        "claim_level": "quoted_in_institutional_release",
        "role": "speaker",
    },
]

CHANNEL_EVALUATION = [
    {
        "channel": "forum_magnum",
        "decision": "implement",
        "reason": "LessWrong, the Alignment Forum, and the EA Forum expose a public GraphQL API. robots.txt disallows /graphiql, not /graphql. Posts are first-person essays with a structured author slug, canonical URL, and pagination by offset. This is the densest missing source of attributable forecasts. Offset is capped at 2000 by the API.",
    },
    {
        "channel": "bluesky",
        "decision": "implement",
        "reason": "public.api.bsky.app allows public reads, needs no key, paginates with a cursor, and returns post text plus a language code. Handles are admitted only from a page already linked to the person. The Mila organization account is kept separate.",
    },
    {
        "channel": "youtube_atom",
        "decision": "reject",
        "reason": "youtube.com/robots.txt disallows /feeds/videos.xml. The Data API needs a key this repository does not have. No adapter was written.",
    },
    {
        "channel": "substack_archive_api",
        "decision": "defer",
        "reason": "Public RSS already collects Substack feeds. One registered feed, sethlazar.substack.com/feed, redirects to an HTML profile and stays invalid_content. A second archive API would mostly duplicate RSS.",
    },
    {
        "channel": "podcast_transcripts",
        "decision": "handoff",
        "reason": "The existing corpus already records speaker_labels_absent on show pages. Transcript attribution belongs with the extraction workstream.",
    },
    {
        "channel": "conference_talk_archives",
        "decision": "defer",
        "reason": "No stable official API with a clear rights path was verified in this pass. YouTube captions are disallowed by robots.txt.",
    },
]
