"""Curated cohort v2026.09.

This file is the reviewed inclusion list. It does not contain guessed ORCID,
OpenAlex, OpenReview, Semantic Scholar, GitHub, or social identifiers.
External IDs are attached later by the resolver when a source corroborates them.
"""

from __future__ import annotations

COHORT_ID = "cohort_2026_09"
COHORT_VERSION = "2026.09.0"
RESOLVER_VERSION = "0.1.0"

# slug, name, organization_type, canonical_url, country
ORGS: list[tuple] = [
    ("openai", "OpenAI", "frontier_lab", "https://openai.com", "US"),
    ("anthropic", "Anthropic", "frontier_lab", "https://www.anthropic.com", "US"),
    ("google-deepmind", "Google DeepMind", "frontier_lab", "https://deepmind.google", "GB"),
    ("google", "Google", "frontier_lab", "https://research.google", "US"),
    ("meta", "Meta", "frontier_lab", "https://ai.meta.com", "US"),
    ("xai", "xAI", "frontier_lab", "https://x.ai", "US"),
    ("ssi", "Safe Superintelligence", "frontier_lab", "https://ssi.inc", "US"),
    ("mistral", "Mistral AI", "frontier_lab", "https://mistral.ai", "FR"),
    ("cohere", "Cohere", "frontier_lab", "https://cohere.com", "CA"),
    ("microsoft-research", "Microsoft Research", "research_lab", "https://www.microsoft.com/en-us/research", "US"),
    ("microsoft-ai", "Microsoft AI", "frontier_lab", "https://www.microsoft.com/en-us/research", "US"),
    ("thinking-machines", "Thinking Machines Lab", "frontier_lab", "https://thinkingmachines.ai", "US"),
    ("character", "Character.AI", "frontier_lab", "https://character.ai", "US"),
    ("nvidia", "NVIDIA", "infrastructure", "https://www.nvidia.com/en-us/research/", "US"),
    ("huggingface", "Hugging Face", "infrastructure", "https://huggingface.co", "US"),
    ("deepseek", "DeepSeek", "frontier_lab", "https://www.deepseek.com", "CN"),
    ("moonshot", "Moonshot AI", "frontier_lab", "https://www.moonshot.ai", "CN"),
    ("zhipu", "Zhipu AI", "frontier_lab", "https://www.zhipuai.cn", "CN"),
    ("alibaba", "Alibaba", "frontier_lab", "https://www.alibabacloud.com", "CN"),
    ("zero-one", "01.AI", "frontier_lab", "https://01.ai", "CN"),
    ("baichuan", "Baichuan", "frontier_lab", "https://www.baichuan-ai.com", "CN"),
    ("minimax", "MiniMax", "frontier_lab", "https://www.minimax.io", "CN"),
    ("bytedance", "ByteDance", "frontier_lab", "https://www.bytedance.com", "CN"),
    ("baidu", "Baidu", "frontier_lab", "https://research.baidu.com", "CN"),
    ("ai21", "AI21 Labs", "frontier_lab", "https://www.ai21.com", "IL"),
    ("sakana", "Sakana AI", "frontier_lab", "https://sakana.ai", "JP"),
    ("kyutai", "Kyutai", "research_lab", "https://kyutai.org", "FR"),
    ("ai2", "Allen Institute for AI", "research_lab", "https://allenai.org", "US"),
    ("eleuther", "EleutherAI", "research_lab", "https://www.eleuther.ai", "US"),
    ("physical-intelligence", "Physical Intelligence", "frontier_lab", "https://www.physicalintelligence.company", "US"),
    ("world-labs", "World Labs", "frontier_lab", "https://www.worldlabs.ai", "US"),
    ("essential-ai", "Essential AI", "frontier_lab", "https://www.essential.ai", "US"),
    ("covariant", "Covariant", "frontier_lab", "https://covariant.ai", "US"),
    ("inflection", "Inflection AI", "frontier_lab", "https://inflection.ai", "US"),
    ("together", "Together AI", "infrastructure", "https://www.together.ai", "US"),
    ("cartesia", "Cartesia", "frontier_lab", "https://cartesia.ai", "US"),
    ("waabi", "Waabi", "frontier_lab", "https://waabi.ai", "CA"),
    ("apple", "Apple", "frontier_lab", "https://machinelearning.apple.com", "US"),
    ("amazon", "Amazon", "frontier_lab", "https://www.amazon.science", "US"),
    ("stanford", "Stanford University", "university", "https://www.stanford.edu", "US"),
    ("berkeley", "University of California, Berkeley", "university", "https://www.berkeley.edu", "US"),
    ("mit", "Massachusetts Institute of Technology", "university", "https://www.mit.edu", "US"),
    ("cmu", "Carnegie Mellon University", "university", "https://www.cmu.edu", "US"),
    ("oxford", "University of Oxford", "university", "https://www.ox.ac.uk", "GB"),
    ("cambridge", "University of Cambridge", "university", "https://www.cam.ac.uk", "GB"),
    ("eth-zurich", "ETH Zurich", "university", "https://ethz.ch", "CH"),
    ("mila", "Mila", "university", "https://mila.quebec", "CA"),
    ("toronto", "University of Toronto", "university", "https://www.utoronto.ca", "CA"),
    ("vector", "Vector Institute", "research_lab", "https://vectorinstitute.ai", "CA"),
    ("nyu", "New York University", "university", "https://www.nyu.edu", "US"),
    ("princeton", "Princeton University", "university", "https://www.princeton.edu", "US"),
    ("harvard", "Harvard University", "university", "https://www.harvard.edu", "US"),
    ("uw", "University of Washington", "university", "https://www.washington.edu", "US"),
    ("columbia", "Columbia University", "university", "https://www.columbia.edu", "US"),
    ("caltech", "California Institute of Technology", "university", "https://www.caltech.edu", "US"),
    ("tsinghua", "Tsinghua University", "university", "https://www.tsinghua.edu.cn", "CN"),
    ("ucl", "University College London", "university", "https://www.ucl.ac.uk", "GB"),
    ("imperial", "Imperial College London", "university", "https://www.imperial.ac.uk", "GB"),
    ("mpi-is", "Max Planck Institute for Intelligent Systems", "research_lab", "https://is.mpg.de", "DE"),
    ("tuebingen", "University of Tübingen", "university", "https://uni-tuebingen.de", "DE"),
    ("jku", "Johannes Kepler University Linz", "university", "https://www.jku.at", "AT"),
    ("kaust", "KAUST", "university", "https://www.kaust.edu.sa", "SA"),
    ("alberta", "University of Alberta", "university", "https://www.ualberta.ca", "CA"),
    ("mcgill", "McGill University", "university", "https://www.mcgill.ca", "CA"),
    ("arc", "Alignment Research Center", "safety_org", "https://www.alignment.org", "US"),
    ("redwood", "Redwood Research", "safety_org", "https://www.redwoodresearch.org", "US"),
    ("metr", "METR", "safety_org", "https://metr.org", "US"),
    ("cais", "Center for AI Safety", "safety_org", "https://www.safe.ai", "US"),
    ("miri", "Machine Intelligence Research Institute", "safety_org", "https://intelligence.org", "US"),
    ("conjecture", "Conjecture", "safety_org", "https://conjecture.dev", "GB"),
    ("uk-aisi", "UK AI Security Institute", "government", "https://www.aisi.gov.uk", "GB"),
    ("epoch", "Epoch AI", "nonprofit", "https://epoch.ai", "US"),
    ("govai", "Centre for the Governance of AI", "nonprofit", "https://www.governance.ai", "GB"),
    ("apollo", "Apollo Research", "safety_org", "https://www.apolloresearch.ai", "GB"),
    ("fli", "Future of Life Institute", "nonprofit", "https://futureoflife.org", "US"),
    ("chai", "Center for Human-Compatible AI", "university", "https://humancompatible.ai", "US"),
    ("cset", "Center for Security and Emerging Technology", "nonprofit", "https://cset.georgetown.edu", "US"),
    ("sfi", "Santa Fe Institute", "research_lab", "https://www.santafe.edu", "US"),
    ("dair", "Distributed AI Research Institute", "nonprofit", "https://www.dair-institute.org", "US"),
    ("georgetown", "Georgetown University", "university", "https://www.georgetown.edu", "US"),
    ("utaustin", "University of Texas at Austin", "university", "https://www.utexas.edu", "US"),
    ("louisville", "University of Louisville", "university", "https://www.louisville.edu", "US"),
    ("lmu", "LMU Munich", "university", "https://www.lmu.de", "DE"),
    ("tu-darmstadt", "TU Darmstadt", "university", "https://www.tu-darmstadt.de", "DE"),
    ("anu", "Australian National University", "university", "https://www.anu.edu.au", "AU"),
    ("genentech", "Genentech", "research_lab", "https://www.gene.com", "US"),
    ("independent", "Independent", "independent", None, None),
]


def person(
    slug: str,
    display_name: str,
    given_name: str,
    family_name: str,
    distinctiveness: str,
    reason: str,
    org: str,
    role: str,
    role_confidence: str,
    keywords: list[str],
    notes: str,
    *,
    status: str = "active",
    focus: str = "frontier_lab",
    extra: list[tuple] | None = None,
    variants: list[str] | None = None,
    reasons: list[str] | None = None,
    claimed_urls: list[dict] | None = None,
) -> dict:
    affiliations = [{"organization_slug": org, "role": role, "basis": "current", "confidence": role_confidence}]
    for item in extra or []:
        affiliations.append(
            {
                "organization_slug": item[0],
                "role": item[1],
                "basis": item[2],
                "confidence": item[3],
            }
        )
    return {
        "slug": slug,
        "display_name": display_name,
        "given_name": given_name,
        "family_name": family_name,
        "name_distinctiveness": distinctiveness,
        "name_variants": variants or [],
        "primary_inclusion_reason": reason,
        "inclusion_reasons": reasons or [reason],
        "inclusion_notes": notes,
        "status": status,
        "focus": focus,
        "affiliations": affiliations,
        "institution_keywords": keywords,
        "claimed_urls": claimed_urls or [],
    }


def _rows() -> list[dict]:
    p = person
    rows = [
        p("dario-amodei", "Dario Amodei", "Dario", "Amodei", "high", "frontier_lab_researcher", "anthropic", "Co-founder and CEO", "high", ["Anthropic", "OpenAI", "Baidu", "Princeton", "Stanford"], "Co-founder of Anthropic and former OpenAI research leader. Public forecasts on frontier risk are first-party."),
        p("daniela-amodei", "Daniela Amodei", "Daniela", "Amodei", "high", "frontier_lab_researcher", "anthropic", "Co-founder and President", "high", ["Anthropic", "OpenAI"], "Co-founder of Anthropic. Included as research-organization leadership, not as a paper-volume author."),
        p("jared-kaplan", "Jared Kaplan", "Jared", "Kaplan", "high", "frontier_model_author", "anthropic", "Co-founder and researcher", "high", ["Anthropic", "Johns Hopkins"], "Co-author of scaling-law and GPT-3 era work; Anthropic co-founder.", reasons=["frontier_model_author", "frontier_lab_researcher"]),
        p("sam-mccandlish", "Sam McCandlish", "Sam", "McCandlish", "high", "frontier_model_author", "anthropic", "Researcher and co-founder", "medium", ["Anthropic", "OpenAI"], "Anthropic co-founder and scaling-research author.", variants=["Samuel McCandlish"]),
        p("tom-brown", "Tom Brown", "Tom", "Brown", "low", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic", "OpenAI"], "Lead author of the GPT-3 paper. Common name; institution match is required.", variants=["Tom B. Brown"]),
        p("chris-olah", "Chris Olah", "Chris", "Olah", "high", "frontier_safety_eval", "anthropic", "Researcher", "high", ["Anthropic", "OpenAI", "Google"], "Mechanistic interpretability researcher. Former OpenAI and Google Brain.", reasons=["frontier_safety_eval", "frontier_lab_researcher"], claimed_urls=[{"namespace": "personal_website", "url": "https://colah.github.io/", "basis": "longstanding_personal_site"}]),
        p("catherine-olsson", "Catherine Olsson", "Catherine", "Olsson", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic", "OpenAI"], "Interpretability and alignment researcher at Anthropic."),
        p("amanda-askell", "Amanda Askell", "Amanda", "Askell", "high", "frontier_safety_eval", "anthropic", "Researcher", "high", ["Anthropic", "OpenAI"], "Alignment and character-research lead associated with Claude's constitution work."),
        p("jack-clark", "Jack Clark", "Jack", "Clark", "low", "frontier_lab_researcher", "anthropic", "Co-founder and policy lead", "high", ["Anthropic", "OpenAI"], "Anthropic co-founder. Writes the public Import AI newsletter on frontier developments.", focus="governance"),
        p("jan-leike", "Jan Leike", "Jan", "Leike", "high", "frontier_safety_eval", "anthropic", "Researcher", "high", ["Anthropic", "OpenAI", "DeepMind"], "Leads alignment-science work. Former OpenAI superalignment lead and DeepMind researcher.", reasons=["frontier_safety_eval", "former_frontier_researcher"]),
        p("sam-bowman", "Sam Bowman", "Sam", "Bowman", "low", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic", "New York University"], "Language-model evaluation researcher. Common given name; institution match required.", variants=["Samuel Bowman", "Samuel R. Bowman"]),
        p("ethan-perez", "Ethan Perez", "Ethan", "Perez", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic", "New York University"], "Model-written evaluations and red-teaming researcher."),
        p("evan-hubinger", "Evan Hubinger", "Evan", "Hubinger", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic", "Machine Intelligence Research Institute"], "Deceptive-alignment researcher now at Anthropic."),
        p("zac-hatfield-dodds", "Zac Hatfield-Dodds", "Zac", "Hatfield-Dodds", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic"], "Anthropic safety and evaluation researcher."),
        p("nova-dassarma", "Nova DasSarma", "Nova", "DasSarma", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic"], "Anthropic security and safety engineering researcher."),
        p("deep-ganguli", "Deep Ganguli", "Deep", "Ganguli", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic"], "Author on Anthropic societal-impact and evaluation papers."),
        p("esin-durmus", "Esin Durmus", "Esin", "Durmus", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic", "Stanford"], "Evaluation researcher at Anthropic, formerly Stanford."),
        p("saurav-kadavath", "Saurav Kadavath", "Saurav", "Kadavath", "high", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic"], "Co-author of Anthropic language-model and calibration papers."),
        p("tom-henighan", "Tom Henighan", "Tom", "Henighan", "high", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic"], "Scaling and multimodal research author associated with Anthropic."),
        p("ben-mann", "Ben Mann", "Ben", "Mann", "low", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic", "OpenAI"], "GPT-3 and Anthropic technical-report author. Common name; institution match required."),
        p("nicholas-joseph", "Nicholas Joseph", "Nicholas", "Joseph", "low", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic"], "Anthropic technical-report author. Institution match required."),
        p("danny-hernandez", "Danny Hernandez", "Danny", "Hernandez", "low", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic", "OpenAI"], "Author of empirical scaling papers. Institution match required.", variants=["Dan Hernandez"]),
        p("mrinank-sharma", "Mrinank Sharma", "Mrinank", "Sharma", "high", "frontier_safety_eval", "anthropic", "Researcher", "medium", ["Anthropic", "Oxford"], "Anthropic safety researcher, formerly at Oxford."),
        p("jascha-sohl-dickstein", "Jascha Sohl-Dickstein", "Jascha", "Sohl-Dickstein", "high", "frontier_model_author", "anthropic", "Researcher", "medium", ["Anthropic", "Google"], "Diffusion-model researcher. Former Google Brain, later Anthropic.", extra=[("google", "Researcher", "former", "high")]),
        p("nelson-elhage", "Nelson Elhage", "Nelson", "Elhage", "high", "former_frontier_researcher", "independent", "Independent researcher", "medium", ["Anthropic"], "Former Anthropic interpretability researcher who remains publicly active.", extra=[("anthropic", "Researcher", "former", "high")]),
        p("durk-kingma", "Durk Kingma", "Durk", "Kingma", "high", "frontier_model_author", "google-deepmind", "Researcher", "medium", ["Google", "DeepMind", "OpenAI", "Anthropic"], "Variational autoencoder and generative-model researcher. Affiliation has moved among OpenAI, Google, and Anthropic.", variants=["Diederik P. Kingma", "Diederik Kingma"], extra=[("openai", "Researcher", "former", "medium")]),
        p("sam-altman", "Sam Altman", "Sam", "Altman", "high", "frontier_lab_researcher", "openai", "CEO", "high", ["OpenAI"], "OpenAI CEO and a primary public forecaster for the lab. Included as research-organization leadership rather than as a publication author.", variants=["Samuel Altman"]),
        p("greg-brockman", "Greg Brockman", "Greg", "Brockman", "high", "frontier_lab_researcher", "openai", "President and co-founder", "high", ["OpenAI"], "OpenAI co-founder and technical leader."),
        p("jakub-pachocki", "Jakub Pachocki", "Jakub", "Pachocki", "high", "frontier_lab_researcher", "openai", "Chief Scientist", "medium", ["OpenAI"], "OpenAI research leader associated with reasoning-model work. Exact title can change."),
        p("mark-chen", "Mark Chen", "Mark", "Chen", "low", "frontier_lab_researcher", "openai", "Research leader", "medium", ["OpenAI"], "OpenAI research leader and GPT-series author. Common name; institution match required."),
        p("wojciech-zaremba", "Wojciech Zaremba", "Wojciech", "Zaremba", "high", "frontier_lab_researcher", "openai", "Co-founder and researcher", "high", ["OpenAI"], "OpenAI co-founder."),
        p("alec-radford", "Alec Radford", "Alec", "Radford", "high", "frontier_model_author", "openai", "Researcher", "high", ["OpenAI"], "Author of GPT-1 and later OpenAI language-model research."),
        p("noam-brown", "Noam Brown", "Noam", "Brown", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI", "Meta", "Carnegie Mellon"], "Multi-agent and reasoning researcher at OpenAI. Former Meta FAIR and CMU."),
        p("lilian-weng", "Lilian Weng", "Lilian", "Weng", "high", "frontier_lab_researcher", "openai", "Researcher", "medium", ["OpenAI"], "OpenAI researcher with a long-running public technical blog.", claimed_urls=[{"namespace": "personal_website", "url": "https://lilianweng.github.io/", "basis": "longstanding_personal_site"}]),
        p("jason-wei", "Jason Wei", "Jason", "Wei", "low", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI", "Google"], "Chain-of-thought and instruction-tuning author. Institution match required."),
        p("hyung-won-chung", "Hyung Won Chung", "Hyung Won", "Chung", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI", "Google"], "Instruction-tuning and language-model author. Former Google, later OpenAI."),
        p("prafulla-dhariwal", "Prafulla Dhariwal", "Prafulla", "Dhariwal", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI"], "Generative-model researcher and GPT-3 co-author."),
        p("jong-wook-kim", "Jong Wook Kim", "Jong Wook", "Kim", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI"], "CLIP and generative-model author at OpenAI."),
        p("aditya-ramesh", "Aditya Ramesh", "Aditya", "Ramesh", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI"], "DALL·E and multimodal-model author."),
        p("long-ouyang", "Long Ouyang", "Long", "Ouyang", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI"], "InstructGPT author."),
        p("ryan-lowe", "Ryan Lowe", "Ryan", "Lowe", "low", "frontier_safety_eval", "openai", "Researcher", "medium", ["OpenAI", "McGill"], "Dialogue and alignment evaluation researcher. Institution match required."),
        p("yang-song", "Yang Song", "Yang", "Song", "low", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI", "Stanford"], "Score-based generative model author. Common name; institution match required."),
        p("sebastien-bubeck", "Sébastien Bubeck", "Sebastien", "Bubeck", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI", "Microsoft"], "Former Microsoft Research leader, later OpenAI. Author of Sparks of AGI.", variants=["Sebastien Bubeck"], extra=[("microsoft-research", "Researcher", "former", "high")], focus="academic"),
        p("aleksander-madry", "Aleksander Mądry", "Aleksander", "Madry", "high", "frontier_safety_eval", "openai", "Researcher", "medium", ["OpenAI", "Massachusetts Institute of Technology"], "Robustness and safety researcher. MIT professor who joined OpenAI.", variants=["Aleksander Madry"], extra=[("mit", "Professor", "relevant", "high")]),
        p("ilya-sutskever", "Ilya Sutskever", "Ilya", "Sutskever", "high", "frontier_lab_researcher", "ssi", "Co-founder", "high", ["Safe Superintelligence", "OpenAI", "Google", "University of Toronto"], "Co-founder of Safe Superintelligence. Former OpenAI chief scientist.", reasons=["frontier_lab_researcher", "former_frontier_researcher"], extra=[("openai", "Chief scientist", "former", "high")]),
        p("daniel-gross", "Daniel Gross", "Daniel", "Gross", "low", "frontier_lab_researcher", "ssi", "Co-founder", "medium", ["Safe Superintelligence"], "SSI co-founder. Common name; do not attach an academic id without institution corroboration."),
        p("john-schulman", "John Schulman", "John", "Schulman", "high", "frontier_lab_researcher", "thinking-machines", "Co-founder and Chief Scientist", "high", ["Thinking Machines", "Anthropic", "OpenAI", "Berkeley"], "His personal site states he is chief scientist at Thinking Machines, previously Anthropic and OpenAI.", reasons=["frontier_lab_researcher", "former_frontier_researcher"], extra=[("anthropic", "Researcher", "former", "high"), ("openai", "Co-founder", "former", "high")], claimed_urls=[{"namespace": "personal_website", "url": "http://joschu.net/", "basis": "personal_homepage_self_description"}]),
        p("mira-murati", "Mira Murati", "Mira", "Murati", "high", "frontier_lab_researcher", "thinking-machines", "Founder and CEO", "high", ["Thinking Machines", "OpenAI"], "Founder of Thinking Machines Lab. Former OpenAI CTO.", extra=[("openai", "Chief Technology Officer", "former", "high")]),
        p("andrej-karpathy", "Andrej Karpathy", "Andrej", "Karpathy", "high", "former_frontier_researcher", "independent", "Independent researcher", "high", ["OpenAI", "Stanford", "Tesla"], "Former OpenAI and Tesla AI lead. Continues to publish technical education and forecasts.", extra=[("openai", "Researcher", "former", "high")], claimed_urls=[{"namespace": "personal_website", "url": "https://karpathy.ai/", "basis": "longstanding_personal_site"}]),
        p("barret-zoph", "Barret Zoph", "Barret", "Zoph", "high", "frontier_lab_researcher", "google", "VP of Research", "medium", ["Google", "OpenAI", "Thinking Machines"], "Press reports in August 2026 placed him at Google after OpenAI and Thinking Machines. Title is recorded at medium confidence.", extra=[("openai", "Research leader", "former", "high"), ("thinking-machines", "Co-founder", "former", "high")]),
        p("liam-fedus", "Liam Fedus", "Liam", "Fedus", "high", "frontier_model_author", "google", "Researcher", "medium", ["Google", "OpenAI"], "Switch Transformer co-author. Worked at Google and OpenAI."),
        p("noam-shazeer", "Noam Shazeer", "Noam", "Shazeer", "high", "frontier_model_author", "google", "Researcher", "medium", ["Google", "Character"], "Transformer co-author and Character.AI co-founder. Current employer is recorded only as a Google-or-Character affiliation pending a primary page.", extra=[("character", "Co-founder", "former", "high")], reasons=["frontier_model_author", "former_frontier_researcher"]),
        p("aidan-gomez", "Aidan Gomez", "Aidan", "Gomez", "high", "frontier_lab_researcher", "cohere", "Co-founder and CEO", "high", ["Cohere", "Oxford", "Google"], "Transformer co-author and Cohere CEO.", variants=["Aidan N. Gomez"], extra=[("google", "Researcher", "former", "medium")]),
        p("nick-frosst", "Nick Frosst", "Nick", "Frosst", "high", "frontier_lab_researcher", "cohere", "Co-founder", "high", ["Cohere", "Google"], "Cohere co-founder. Former Google Brain."),
        p("ivan-zhang", "Ivan Zhang", "Ivan", "Zhang", "low", "frontier_lab_researcher", "cohere", "Co-founder", "medium", ["Cohere"], "Cohere co-founder. Common name; institution match required."),
        p("joelle-pineau", "Joelle Pineau", "Joelle", "Pineau", "high", "frontier_lab_researcher", "mcgill", "Professor", "high", ["McGill", "Meta", "Mila"], "Professor at McGill and former Meta FAIR research leader. A later industry role is not asserted here.", extra=[("meta", "Research leader", "former", "medium"), ("mila", "Faculty", "relevant", "medium")], focus="academic"),
        p("ashish-vaswani", "Ashish Vaswani", "Ashish", "Vaswani", "high", "frontier_model_author", "essential-ai", "Co-founder", "medium", ["Google", "Essential AI", "Adept"], "First author of Attention Is All You Need. Later founded Essential AI.", extra=[("google", "Researcher", "former", "high")]),
        p("llion-jones", "Llion Jones", "Llion", "Jones", "high", "frontier_model_author", "sakana", "Co-founder", "high", ["Sakana", "Google"], "Transformer co-author and Sakana AI co-founder.", extra=[("google", "Researcher", "former", "high")]),
        p("niki-parmar", "Niki Parmar", "Niki", "Parmar", "high", "frontier_model_author", "essential-ai", "Researcher", "medium", ["Google", "Essential AI", "Adept"], "Transformer co-author.", extra=[("google", "Researcher", "former", "high")]),
        p("jakob-uszkoreit", "Jakob Uszkoreit", "Jakob", "Uszkoreit", "high", "frontier_model_author", "independent", "Independent researcher", "medium", ["Google"], "Transformer co-author. Former Google Brain. Later company affiliation is not asserted."),
        p("illia-polosukhin", "Illia Polosukhin", "Illia", "Polosukhin", "high", "frontier_model_author", "independent", "Independent researcher", "medium", ["Google"], "Transformer co-author. Former Google Brain.", extra=[("google", "Researcher", "former", "high")]),
        p("lukasz-kaiser", "Łukasz Kaiser", "Lukasz", "Kaiser", "high", "frontier_model_author", "openai", "Researcher", "medium", ["OpenAI", "Google"], "Transformer and attention-model author. Former Google, later OpenAI.", variants=["Lukasz Kaiser"], extra=[("google", "Researcher", "former", "high")]),
        p("colin-raffel", "Colin Raffel", "Colin", "Raffel", "high", "frontier_model_author", "toronto", "Faculty", "medium", ["University of Toronto", "Google", "Hugging Face"], "T5 author. Former Google Brain.", extra=[("google", "Researcher", "former", "high")], focus="academic"),
    ]
    return rows
