export {
  computeHistoricalRevision,
  computeProbabilityDistribution,
  computeProbabilityDistribution as computeExplicitNumericDistribution,
  computeQuantityForecast,
  computeStatementVolume,
  computeTimelineForecast,
  discoverQualitativeGroups,
  discoverQuestionTrends,
  listUnpooledForecasts,
  median,
} from "./trend-engine";

export type {
  DiscoveredTrend,
  Exclusion,
  IncludedEstimate,
  NumericTrendResult,
  QualitativeGroup,
  RepeatRecord,
  RevisionChain,
  RevisionEdge,
  RevisionLink,
  RevisionPoint,
  RevisionResult,
  TrendCandidate,
  TrendCoverage,
  TrendScope,
  UnpooledForecast,
  VolumeRow,
} from "./trend-engine";
