"""Metadata catalog of public Max Planck Institute for Security and Privacy pages.

Hosts are www.mpi-sp.org and mpi-sp.org. Eligible pages are AI,
machine-learning, security-research, news, and publication HTML. A row keeps
the title, publisher, canonical URL, date, and rights label. Page bodies,
abstracts, PDFs, quotes, transcripts, and chart data are not stored. The live
URL is stored as confirmed; a different rel=canonical does not replace it.

Each stored URL was confirmed with one bounded GET that returned HTML and
stayed on those hosts. robots.txt for User-agent * states no disallow.
An HTML document served in place of robots.txt does not allow a fetch. A
Cloudflare challenge, a captcha, an authentication wall, a non-HTML shell,
a robots disallow, or a redirect off those hosts is not stored. An empty
entries list is valid when every fetch is blocked. Login walls, person
profiles, and other hosts are not stored. This module does not fetch and it
does not bypass a challenge, a captcha, authentication, or robots.

Rights stay unknown unless the page states a reuse licence.
``creative_commons_attribution`` means CC BY alone, including a
https://creativecommons.org/licenses/by/4.0/ URL. ``creative_commons`` means
CC0, CC BY-SA, or a permissive mix of those, including CC BY together with
CC0 or CC BY-SA. A sole CC BY-NC, CC BY-ND, CC BY-NC-SA, or CC BY-NC-ND keeps
that token. A hyphen is a word boundary, so CC BY does not match CC BY-NC and
licenses/by does not match licenses/by-nc. Two different restricted deeds stay
unknown. A software licence beside any Creative Commons deed stays unknown.
Two software licences stay unknown. A permissive anchor on a restricted deed
URL or a public-domain mark URL stays unknown. A CC0 anchor on a
publicdomain/mark URL stays unknown. A generic creativecommons.org/licenses
URL is not a deed: a missing slash, http, a www host, and a query string stay
on that generic path, and the anchor text does not count. Text elsewhere on
the page still counts. A specific deed URL still counts. A photo credit,
caption credit, or image credit that names someone else's licence does not
count, including Photo credit: UNDRR, CC BY-NC-ND 2.0 and Photo: UNDRR,
CC BY-NC-ND 2.0. A page licence stated outside that credit still counts.
The Public Domain Mark is not CC0. ``uk_ogl`` requires the British phrase
Open Government Licence. American spelling License stays unknown.
``us_government_work`` requires an explicit rights metadata field. ``mit``,
``apache-2.0``, and ``mpl-2.0`` stay their own tokens only for a sole
software licence. Bare MIT stays unknown. Licensed under the MIT License is
mit. Apache License, Version 2.0 is apache-2.0.

Updated, modified, and copyright years are not publication dates. Script,
style, and comment text does not count. A missing publication date stays
unknown. This module is not a belief collector. ``runner_wired`` stays false.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from datetime import date
from html import unescape
from pathlib import Path
from urllib.parse import urlparse

from pdoom_pipeline.urls import hostname_is_blocked

CATALOG_ID = "mpi_sp_pages"
CATALOG_FILENAME = "mpi_sp_pages.json"
RUNNER_WIRED = False
PUBLISHER = "Max Planck Institute for Security and Privacy"
UNKNOWN_DATE = "unknown"
RIGHTS_UNKNOWN = "unknown"
RIGHTS_CREATIVE_COMMONS = "creative_commons"
RIGHTS_CC_ATTRIBUTION = "creative_commons_attribution"
RIGHTS_CC_BY_NC = "cc_by_nc"
RIGHTS_CC_BY_ND = "cc_by_nd"
RIGHTS_CC_BY_NC_ND = "cc_by_nc_nd"
RIGHTS_CC_BY_NC_SA = "cc_by_nc_sa"
RIGHTS_UK_OGL = "uk_ogl"
RIGHTS_US_GOVERNMENT_WORK = "us_government_work"
RIGHTS_MIT = "mit"
RIGHTS_APACHE = "apache-2.0"
RIGHTS_MPL = "mpl-2.0"
RIGHTS_LABELS = frozenset(
    {
        RIGHTS_UNKNOWN,
        RIGHTS_CREATIVE_COMMONS,
        RIGHTS_CC_ATTRIBUTION,
        RIGHTS_CC_BY_NC,
        RIGHTS_CC_BY_ND,
        RIGHTS_CC_BY_NC_ND,
        RIGHTS_CC_BY_NC_SA,
        RIGHTS_UK_OGL,
        RIGHTS_US_GOVERNMENT_WORK,
        RIGHTS_MIT,
        RIGHTS_APACHE,
        RIGHTS_MPL,
    }
)
OFFICIAL_HOSTS = frozenset({"mpi-sp.org", "www.mpi-sp.org"})
MAX_TEXT_CHARS = 400
MAX_DESCRIPTION_CHARS = 800
# Confirmed from https://www.mpi-sp.org/robots.txt. The body is a robots file
# with no Disallow. An HTML document served in its place does not allow a fetch.
CONFIRMED_ROBOTS = """# Generated by CMS-App (default)
User-agent: *
Sitemap: https://www.mpi-sp.org/sitemap.xml
"""
CATALOG_DESCRIPTION = (
    "Metadata for public Max Planck Institute for Security and Privacy pages on www.mpi-sp.org and mpi-sp.org. "
    "AI, machine-learning, security-research, news, and publication HTML pages are eligible. "
    "Rows keep a title, publisher, canonical URL, date, and rights. Page bodies are not stored. "
    "Each stored URL was confirmed with one bounded GET that returned HTML and stayed on those hosts. "
    "robots.txt states no disallow. An HTML document in place of robots.txt does not allow a fetch. "
    "creative_commons means CC0, CC BY-SA, or a permissive mix of those. "
    "creative_commons_attribution means CC BY alone. "
    "A missing date is unknown. Updated, modified, and copyright years are not publication dates. "
    "runner_wired is false."
)

_CATALOG_FIELDS = frozenset({"catalog_id", "description", "runner_wired", "entries"})
_ENTRY_FIELDS = frozenset({"title", "publisher", "canonical_url", "date", "rights"})
_FORBIDDEN_KEYS = frozenset(
    {
        "abstract",
        "body",
        "chart",
        "chart_data",
        "content",
        "excerpt",
        "full_text",
        "html",
        "page",
        "page_text",
        "pdf",
        "pdoom",
        "p_doom",
        "probability",
        "quotation",
        "quote",
        "summary",
        "text",
        "transcript",
        "transcript_text",
    }
)
_HTML_TYPES = frozenset({"text/html", "application/xhtml+xml"})
_PUBLICATION_META = (
    "article:published_time",
    "citation_publication_date",
    "dcterms.issued",
    "dc.date.issued",
)
_RIGHTS_META = frozenset({"rights", "dc.rights", "dcterms.rights"})
_LICENSE_META = frozenset(
    {"license", "licence", "dcterms.license", "dcterms.licence", "dc.rights", "dcterms.rights", "rights"}
)
_TITLE_KEYS = ("og:title", "citation_title", "twitter:title", "dcterms.title")
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_DATE_PREFIX = re.compile(r"^(\d{4}-\d{2}-\d{2})")
_COMMENT = re.compile(r"(?is)<!--.*?-->")
_SCRIPT_STYLE = re.compile(r"(?is)<(script|style|noscript)\b[^>]*>.*?</\1>")
_TAG = re.compile(r"(?is)<[^>]+>")
_META = re.compile(r"(?is)<meta\b[^>]*>")
_LINK = re.compile(r"(?is)<(?:link|a)\b[^>]*>")
_ANCHOR_ELEMENT = re.compile(r"(?is)<a\b([^>]*)>(.*?)</a>")
_H1 = re.compile(r"(?is)<h1\b[^>]*>(.*?)</h1>")
_TITLE = re.compile(r"(?is)<title\b[^>]*>(.*?)</title>")
_ATTR = re.compile(
    r"""(?is)([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))"""
)
_GENERIC_CC_HOSTS = frozenset({"creativecommons.org", "www.creativecommons.org"})
_SITE_SUFFIXES = (
    " | max planck institute for security and privacy",
    " - max planck institute for security and privacy",
    " – max planck institute for security and privacy",
    " — max planck institute for security and privacy",
    " | max-planck-institut für sicherheit und privatsphäre",
    " - max-planck-institut für sicherheit und privatsphäre",
    " | mpi-sp",
    " - mpi-sp",
)
_PUBLISHER_WORD = re.compile(
    r"(?i)max[\s-]*planck[\s-]*(?:institute\s+for\s+security\s+and\s+privacy|"
    r"institut\s+f(?:ü|ue)r\s+sicherheit\s+und\s+privatsph(?:ä|ae)re)"
)
_EXACT_PATHS = frozenset(
    {
        "/6054/newsroom",
        "/89706/Blog",
        "/70266/Research-Areas",
        "/imprs",
    }
)
_NEWS_ARTICLE = re.compile(r"^/[0-9]+/news_publication_[0-9]+_transferred$")
_BLOG_SLUG = re.compile(r"^/blog/[A-Za-z0-9][A-Za-z0-9-]*$")
# CMS blog posts use a numeric id and a title slug that contains an underscore.
_BLOG_CMS = re.compile(r"^/[0-9]+/[A-Za-z][A-Za-z0-9_-]*_[A-Za-z0-9_-]*$")
# Some news articles use a long title slug instead of news_publication_*.
# The minimum length keeps short institutional paths such as /4200/about-us out.
_NEWS_SLUG = re.compile(r"^/[0-9]+/[A-Za-z][A-Za-z0-9-]{39,}$")
_LOGIN_MARKERS = (
    "/login",
    "/log-in",
    "/signin",
    "/sign-in",
    "/account",
    "/wp-login",
    "/users/sign_in",
    "/user/login",
)
_PERSON_MARKERS = ("/person", "/people", "/persons", "/profiles")
_DOWNLOAD_SUFFIXES = (
    ".pdf",
    ".zip",
    ".csv",
    ".json",
    ".xml",
    ".doc",
    ".docx",
    ".ppt",
    ".pptx",
    ".xls",
    ".xlsx",
    ".epub",
    ".mp3",
    ".mp4",
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".webp",
    ".svg",
    ".ico",
    ".bib",
)
_CHALLENGE_MARKERS = (
    "just a moment",
    "performing security verification",
    "enable javascript and cookies",
    "challenge-platform",
    "cf-mitigated",
    "cf-turnstile",
    "checking your browser",
    "attention required",
    "sorry, you have been blocked",
    "sg-captcha",
    "sgcaptcha",
    "/.well-known/sgcaptcha/",
    "akamaighost",
    "errors.edgesuite.net",
    "are you a robot",
    "bot detection",
)
_AUTH_TITLE_MARKERS = (
    "log in",
    "sign in",
    "authentication required",
    "access denied",
)
_DASHES = str.maketrans(
    {
        "\u00a0": " ",
        "\u2010": "-",
        "\u2011": "-",
        "\u2012": "-",
        "\u2013": "-",
        "\u2014": "-",
        "\u2212": "-",
    }
)
# Longer deeds are listed first. (?!-) and (?![a-z0-9-]) keep CC BY and
# licenses/by from matching CC BY-NC and licenses/by-nc.
_TEXT_DEEDS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("by-nc-nd", re.compile(r"(?<![a-z0-9])cc[\s-]*by[\s-]*nc[\s-]*nd(?![a-z0-9])")),
    (
        "by-nc-nd",
        re.compile(r"creative commons attribution[\s-]*non[\s-]*commercial[\s-]*no[\s-]*deriv"),
    ),
    ("by-nc-sa", re.compile(r"(?<![a-z0-9])cc[\s-]*by[\s-]*nc[\s-]*sa(?![a-z0-9])")),
    (
        "by-nc-sa",
        re.compile(r"creative commons attribution[\s-]*non[\s-]*commercial[\s-]*share[\s-]*alike"),
    ),
    ("by-nc", re.compile(r"(?<![a-z0-9])cc[\s-]*by[\s-]*nc(?![a-z0-9-])")),
    ("by-nc", re.compile(r"creative commons attribution[\s-]*non[\s-]*commercial")),
    ("by-nd", re.compile(r"(?<![a-z0-9])cc[\s-]*by[\s-]*nd(?![a-z0-9])")),
    ("by-nd", re.compile(r"creative commons attribution[\s-]*no[\s-]*deriv")),
    ("by-sa", re.compile(r"(?<![a-z0-9])cc[\s-]*by[\s-]*sa(?![a-z0-9])")),
    ("by-sa", re.compile(r"creative commons attribution[\s-]*share[\s-]*alike")),
    ("zero", re.compile(r"(?<![a-z0-9])(?:cc[\s-]*0|cc[\s-]*zero)(?![a-z0-9])")),
    ("zero", re.compile(r"creative commons(?:\s+public\s+domain)?[\s-]*zero(?![a-z])")),
    ("by", re.compile(r"(?<![a-z0-9])cc[\s-]*by(?!-)(?![a-z0-9])")),
    ("by", re.compile(r"creative commons attribution(?![\s-]*(?:non|no[\s-]*deriv|share))")),
    ("mark", re.compile(r"public domain mark")),
)
_URL_DEEDS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("by-nc-nd", re.compile(r"creativecommons\.org/licenses/by-nc-nd(?![a-z0-9-])")),
    ("by-nc-sa", re.compile(r"creativecommons\.org/licenses/by-nc-sa(?![a-z0-9-])")),
    ("by-nc", re.compile(r"creativecommons\.org/licenses/by-nc(?![a-z0-9-])")),
    ("by-nd", re.compile(r"creativecommons\.org/licenses/by-nd(?![a-z0-9-])")),
    ("by-sa", re.compile(r"creativecommons\.org/licenses/by-sa(?![a-z0-9-])")),
    ("by", re.compile(r"creativecommons\.org/licenses/by(?!-)(?![a-z0-9])")),
    ("zero", re.compile(r"creativecommons\.org/publicdomain/zero(?![a-z0-9-])")),
    ("mark", re.compile(r"creativecommons\.org/publicdomain/mark(?![a-z0-9-])")),
)
_RESTRICTED = frozenset({"by-nc", "by-nd", "by-nc-sa", "by-nc-nd"})
_PERMISSIVE = frozenset({"by", "by-sa", "zero"})
_RESTRICTED_TOKENS = {
    "by-nc": RIGHTS_CC_BY_NC,
    "by-nd": RIGHTS_CC_BY_ND,
    "by-nc-sa": RIGHTS_CC_BY_NC_SA,
    "by-nc-nd": RIGHTS_CC_BY_NC_ND,
}
_OGL_PHRASE = re.compile(r"open government licence(?![a-z])")
_US_GOV_WORK = re.compile(r"\b(?:united states|u\.s\.|us)\s+government\s+work\b")
_NEGATED_US_GOV = re.compile(r"\bnot\s+(?:a\s+)?(?:united states|u\.s\.|us)\s+government\s+work\b")
_MIT = re.compile(
    r"(?<!modified )(?:\bmit licen[cs]e\b|\blicen[cs]ed under (?:the )?mit licen[cs]e\b)"
)
_MIT_URL = re.compile(r"(?:opensource\.org/licenses/mit|spdx\.org/licenses/mit)(?![a-z0-9-])")
_APACHE = re.compile(
    r"(?<![a-z0-9])apache[\s-]*2\.0(?![a-z0-9])|\bapache licen[cs]e,?\s*(?:version\s+)?2(?:\.0)?\b"
)
_APACHE_URL = re.compile(
    r"(?:apache\.org/licenses/license-2\.0|spdx\.org/licenses/apache-2\.0)(?![a-z0-9-])"
)
_MPL = re.compile(r"(?<![a-z0-9])mpl-2\.0(?![a-z0-9])|\bmozilla public licen[cs]e\s*2\.0\b")
_MPL_URL = re.compile(r"(?:mozilla\.org/mpl/2\.0|spdx\.org/licenses/mpl-2\.0)(?![a-z0-9-])")
_CREDIT_PHRASE = re.compile(
    r"(?i)\b(?:photo|image|caption)\s+credits?\b|\b(?:photo|image|caption)\s*:"
)
_CREDIT_BLOCK = re.compile(r"(?is)<(p|li|figcaption|td|dd|figure)\b([^>]*)>(.*?)</\1>")
_CREDIT_CLASS = re.compile(
    r"(?i)(?:photo[\s_-]*credit|image[\s_-]*credit|caption[\s_-]*credit|wp-caption)"
)
_META_INFO_DATE = re.compile(
    r'(?is)<div\b[^>]*\bclass\s*=\s*["\'][^"\']*\bmeta-information\b[^"\']*["\'][^>]*>'
    r'.{0,500}?'
    r'<span\b[^>]*\bclass\s*=\s*["\']\s*date\s*["\'][^>]*>\s*([^<]+?)\s*</span>'
)
_TIME_DATE = re.compile(r"(?is)<time\b([^>]*)>(.*?)</time>")
_MONTHS = {
    "january": 1,
    "february": 2,
    "march": 3,
    "april": 4,
    "may": 5,
    "june": 6,
    "july": 7,
    "august": 8,
    "september": 9,
    "october": 10,
    "november": 11,
    "december": 12,
    "januar": 1,
    "februar": 2,
    "märz": 3,
    "marz": 3,
    "mai": 5,
    "juni": 6,
    "juli": 7,
    "oktober": 10,
    "dezember": 12,
}
_BLOCK_BOUNDARY = re.compile(
    r"(?i)</(?:p|figcaption|li|dd|dt|h[1-6]|caption|blockquote|td|th)>"
    r"|<(?:p|div|article|section|li|h[1-6]|figcaption|blockquote)\b"
)


class CatalogError(ValueError):
    """A catalog row or page failed the Max Planck Institute for Security and Privacy page rules."""


def catalog_path() -> Path:
    return Path(__file__).resolve().parents[3] / "data" / "catalogs" / CATALOG_FILENAME


def load_catalog(path: Path | None = None) -> dict:
    target = catalog_path() if path is None else Path(path)
    document = json.loads(target.read_text(encoding="utf-8"))
    return validate_catalog(document)


def is_official_host(hostname: str) -> bool:
    """True only for www.mpi-sp.org and mpi-sp.org."""

    host = (hostname or "").strip().lower().rstrip(".")
    if not host or ".." in host or hostname_is_blocked(host):
        return False
    return host in OFFICIAL_HOSTS


def is_html_content_type(content_type: object) -> bool:
    if not isinstance(content_type, str) or not content_type.strip():
        return False
    base = content_type.split(";", 1)[0].strip().casefold()
    return base in _HTML_TYPES


def is_challenge_page(page_html: str) -> bool:
    """True when the response is an interstitial challenge rather than the page."""

    if not isinstance(page_html, str) or not page_html.strip():
        return False
    lowered = page_html.casefold()
    return any(marker in lowered for marker in _CHALLENGE_MARKERS)


def is_auth_wall(page_html: str) -> bool:
    """True when the response is a login or authentication wall."""

    if not isinstance(page_html, str) or not page_html.strip():
        return False
    title_match = _TITLE.search(page_html[:8000])
    title = title_match.group(1).casefold() if title_match else ""
    if any(marker in title for marker in _AUTH_TITLE_MARKERS):
        return True
    head = page_html[:4000].casefold()
    return 'type="password"' in head and "<article" not in page_html[:12000].casefold()


def looks_like_html_document(page_html: str) -> bool:
    """True when the body is an HTML document rather than a non-HTML shell."""

    if not isinstance(page_html, str):
        return False
    sample = page_html.lstrip()[:1200].casefold()
    if not sample or sample.startswith("{") or sample.startswith("["):
        return False
    return (
        "<html" in sample
        or "<!doctype" in sample
        or "<title" in sample
        or "<meta" in sample
        or "<h1" in sample
    )


def robots_allows(body: str, path: str) -> bool:
    """True when User-agent * does not disallow path.

    An HTML document or a challenge page served in place of robots.txt does
    not allow a fetch. A sitemap line with no disallow allows the path.
    """

    if not isinstance(body, str) or not isinstance(path, str) or not path.startswith("/"):
        return False
    sample = body.lstrip()[:800].casefold()
    if sample.startswith("<!doctype") or sample.startswith("<html") or "<html" in sample:
        return False
    if is_challenge_page(body[:8000]):
        return False
    target = path or "/"
    allowed = 0
    disallowed = 0
    for kind, prefix in _wildcard_rules(body):
        if prefix and target.startswith(prefix):
            if kind == "allow":
                allowed = max(allowed, len(prefix))
            else:
                disallowed = max(disallowed, len(prefix))
    return disallowed <= allowed


def response_stores_a_page(
    *,
    status: object,
    content_type: object,
    page_html: object,
    headers: Mapping[str, str] | None = None,
) -> bool:
    """A page is stored only from HTML that is not a challenge response.

    HTTP 202, a non-200 status, a Cloudflare or SiteGround challenge, a
    bot-detection interstitial, an authentication wall, a non-HTML shell,
    and an Akamai 403 are not stored.
    """

    if status != 200 or not isinstance(page_html, str) or not page_html.strip():
        return False
    if not is_html_content_type(content_type) or not looks_like_html_document(page_html):
        return False
    if is_challenge_page(page_html) or is_auth_wall(page_html):
        return False
    if headers:
        for key, value in headers.items():
            name = str(key).casefold()
            token = str(value).casefold()
            if name == "cf-mitigated" and "challenge" in token:
                return False
            if name == "sg-captcha":
                return False
            if name == "server" and "akamai" in token and status == 403:
                return False
    return True


def record_from_response(
    *,
    status: object,
    content_type: object,
    page_html: object,
    page_url: str,
    headers: Mapping[str, str] | None = None,
    final_url: str | None = None,
    robots_txt: str | None = None,
) -> dict | None:
    """Return metadata when the response is page HTML on an official host.

    A challenge, a captcha, an authentication wall, an HTTP error, a non-HTML
    body, a login page, a person profile, a robots disallow, an HTML document
    served as robots.txt, or an off-host URL is not stored.
    """

    if not isinstance(page_url, str):
        return None
    if not is_official_host(urlparse(page_url).hostname or ""):
        return None
    target = page_url
    if final_url is not None:
        if not isinstance(final_url, str) or not is_official_host(urlparse(final_url).hostname or ""):
            return None
        target = final_url
    if robots_txt is not None and not robots_allows(robots_txt, urlparse(target).path or "/"):
        return None
    if not response_stores_a_page(
        status=status,
        content_type=content_type,
        page_html=page_html,
        headers=headers,
    ):
        return None
    assert isinstance(page_html, str)
    try:
        return page_record(page_html, page_url=target)
    except CatalogError:
        return None


def rights_from_page(page_text: str) -> str:
    """Return a rights label from a reuse licence the page itself states.

    Restricted deeds are checked before permissive ones. A hyphen is a word
    boundary, so CC BY-NC is not CC BY and licenses/by does not match
    licenses/by-nc. A photo credit, caption credit, or image credit is not a
    licence for the page. A generic creativecommons.org/licenses URL is not a
    deed, and the visible text of that anchor does not count. Text elsewhere
    on the page still counts. A specific deed URL still counts. Mixed
    restricted and permissive text stays unknown. A software licence beside
    any Creative Commons deed stays unknown. Two software licences stay
    unknown. Two different restricted deeds stay unknown. Script, style, and
    comment text does not count.
    """

    if not isinstance(page_text, str):
        raise CatalogError("page text must be a string")
    visible = _without_credit_regions(_without_hidden(page_text))
    plain = _plain(_without_generic_cc_license_anchors(visible)).casefold().translate(_DASHES)
    codes = _text_codes(plain)
    hrefs = [href for href in _hrefs(visible) if not _is_generic_cc_licenses_url(href)]
    for href in hrefs:
        codes |= _url_codes(href.casefold().translate(_DASHES))
    licence_bits: list[str] = []
    us_gov = _states_us_government_work(page_text)
    for key, content in _meta_pairs(visible):
        if key not in _LICENSE_META:
            continue
        chunk = _fold_licence_text(content)
        licence_bits.append(chunk)
        codes |= _text_codes(chunk)
        codes |= _url_codes(chunk)
    scanned = " ".join([plain, *licence_bits, *(href.casefold() for href in hrefs)])
    mit = bool(_MIT.search(scanned) or any(_MIT_URL.search(href.casefold()) for href in hrefs))
    apache = bool(_APACHE.search(scanned) or any(_APACHE_URL.search(href.casefold()) for href in hrefs))
    mpl = bool(_MPL.search(scanned) or any(_MPL_URL.search(href.casefold()) for href in hrefs))
    return _label(
        codes,
        mit=mit,
        apache=apache,
        mpl=mpl,
        ogl=bool(_OGL_PHRASE.search(plain)),
        us_gov=us_gov,
    )


def publication_date_from_page(page_html: str) -> str:
    """Return a YYYY-MM-DD publication date, or unknown when the page has none.

    article:modified_time, og:updated_time, a last-updated line, and a copyright
    year are not publication dates. A date inside script, style, or comment
    text does not count. Disagreeing publication dates stay unknown.
    """

    if not isinstance(page_html, str):
        raise CatalogError("page must be text")
    visible = _without_hidden(page_html)
    found: list[str] = []
    for key, content in _meta_pairs(visible):
        if key not in _PUBLICATION_META:
            continue
        parsed = _iso_day(content)
        if parsed:
            found.append(parsed)
    for raw in _META_INFO_DATE.findall(visible):
        parsed = _human_date(_clean_text(raw))
        if parsed:
            found.append(parsed)
    for attrs, body in _TIME_DATE.findall(visible):
        class_tokens = set(_attrs(f"<time {attrs}>").get("class", "").casefold().split())
        if "date" not in class_tokens or "attribute" in class_tokens:
            continue
        parsed = _human_date(_clean_text(body))
        if parsed is None:
            parsed = _iso_day(_attrs(f"<time {attrs}>").get("datetime", ""))
        if parsed:
            found.append(parsed)
    distinct = set(found)
    if len(distinct) == 1:
        return next(iter(distinct))
    return UNKNOWN_DATE


def title_from_page(page_html: str) -> str:
    if not isinstance(page_html, str):
        raise CatalogError("page must be text")
    visible = _without_hidden(page_html)
    metas = _metas(visible)
    for key in _TITLE_KEYS:
        title = _clean_title(metas.get(key, ""))
        if title:
            return title
    heading = _H1.search(visible)
    if heading:
        title = _clean_title(_TAG.sub(" ", heading.group(1)))
        if title:
            return title
    title_tag = _TITLE.search(visible)
    if title_tag:
        title = _clean_title(_TAG.sub(" ", title_tag.group(1)))
        if title:
            return title
    raise CatalogError("title is required")


def publisher_from_page(page_html: str) -> str:
    """Return the institute name when the page states it.

    A person named on the page is not the publisher. The hostname alone is
    not the publisher.
    """

    if not isinstance(page_html, str):
        raise CatalogError("page must be text")
    visible = _without_hidden(page_html)
    if _PUBLISHER_WORD.search(_plain(visible)):
        return PUBLISHER
    metas = _metas(visible)
    for key in ("og:site_name", "citation_publisher", "publisher"):
        if _PUBLISHER_WORD.search(metas.get(key, "")):
            return PUBLISHER
    raise CatalogError("publisher is required")


def page_record(page_html: str, *, page_url: str) -> dict:
    """Return metadata for one confirmed page.

    The record does not include the document body. ``page_url`` is the live
    URL that returned HTML. A rel=canonical pointing somewhere else is not used.
    """

    if is_challenge_page(page_html):
        raise CatalogError("challenge page is not stored")
    record = {
        "title": title_from_page(page_html),
        "publisher": publisher_from_page(page_html),
        "canonical_url": validate_canonical_url(page_url),
        "date": publication_date_from_page(page_html),
        "rights": rights_from_page(page_html),
    }
    return validate_entry(record)


def validate_catalog(document: dict) -> dict:
    if not isinstance(document, dict):
        raise CatalogError("catalog must be an object")
    _reject_stored_body(document)
    if set(document) != _CATALOG_FIELDS:
        raise CatalogError("catalog fields must be catalog_id, description, runner_wired, and entries")
    if document.get("catalog_id") != CATALOG_ID:
        raise CatalogError(f"catalog_id must be {CATALOG_ID}")
    description = document.get("description")
    if not isinstance(description, str) or not description.strip() or description != description.strip():
        raise CatalogError("description is required")
    if description != CATALOG_DESCRIPTION:
        raise CatalogError("description must match the catalog contract")
    if len(description) > MAX_DESCRIPTION_CHARS:
        raise CatalogError("description is too long")
    if document.get("runner_wired") is not False:
        raise CatalogError("runner_wired must be false")
    entries = document.get("entries")
    if not isinstance(entries, list):
        raise CatalogError("entries must be a list")
    seen: set[str] = set()
    order: list[tuple[str, str]] = []
    for index, entry in enumerate(entries):
        validate_entry(entry)
        url = entry["canonical_url"]
        if url in seen:
            raise CatalogError(f"duplicate canonical URL: {url}")
        seen.add(url)
        order.append((_sort_date(entry["date"]), url))
        if index and order[-1] < order[-2]:
            raise CatalogError("entries must be ordered by date, then canonical URL")
    return document


def validate_entry(entry: dict) -> dict:
    if not isinstance(entry, dict):
        raise CatalogError("entry must be an object")
    _reject_stored_body(entry, path="entry")
    if set(entry) != _ENTRY_FIELDS:
        raise CatalogError("entry fields must be title, publisher, canonical URL, date, and rights")
    _require_text(entry.get("title"), "title", MAX_TEXT_CHARS)
    if entry.get("publisher") != PUBLISHER:
        raise CatalogError(f"publisher must be {PUBLISHER}")
    validate_canonical_url(entry.get("canonical_url"))
    validate_date(entry.get("date"))
    if entry.get("rights") not in RIGHTS_LABELS:
        raise CatalogError("rights must be a known label or unknown")
    return entry


def validate_date(value: object) -> str:
    if value == UNKNOWN_DATE:
        return UNKNOWN_DATE
    if not isinstance(value, str) or _DATE.fullmatch(value) is None or _iso_day(value) is None:
        raise CatalogError(f"date must be YYYY-MM-DD or {UNKNOWN_DATE}")
    return value


def validate_canonical_url(url: object) -> str:
    if not isinstance(url, str) or not url or url != url.strip():
        raise CatalogError(
            "canonical URL must be a public institute AI, machine-learning, security-research, news, or publication page"
        )
    parsed = urlparse(url)
    host = (parsed.hostname or "").lower().rstrip(".")
    path = parsed.path or ""
    if (
        parsed.scheme != "https"
        or not is_official_host(host)
        or parsed.netloc.lower() != host
        or parsed.username
        or parsed.password
        or parsed.query
        or parsed.fragment
        or parsed.port is not None
        or not _public_section_path(path)
    ):
        raise CatalogError(
            "canonical URL is not a public institute AI, machine-learning, security-research, "
            f"news, or publication page: {url}"
        )
    return url


def _public_section_path(path: str) -> bool:
    if not path.startswith("/") or ".." in path or "//" in path or "\\" in path or "%" in path:
        return False
    if path != "/" and path.endswith("/"):
        return False
    lowered = path.casefold()
    if lowered.endswith(_DOWNLOAD_SUFFIXES) or lowered.endswith(".rss"):
        return False
    if any(marker in lowered for marker in _LOGIN_MARKERS):
        return False
    if any(lowered == marker or lowered.startswith(marker + "/") for marker in _PERSON_MARKERS):
        return False
    if lowered == "/challenge" or lowered.startswith("/challenge/") or "/selfservice" in lowered:
        return False
    if lowered.startswith("/search") or "/search-result" in lowered:
        return False
    if path in _EXACT_PATHS:
        return True
    return bool(
        _NEWS_ARTICLE.fullmatch(path)
        or _BLOG_SLUG.fullmatch(path)
        or _BLOG_CMS.fullmatch(path)
        or _NEWS_SLUG.fullmatch(path)
    )


def _label(
    codes: set[str],
    *,
    mit: bool,
    apache: bool,
    mpl: bool,
    ogl: bool,
    us_gov: bool,
) -> str:
    if "mark" in codes:
        return RIGHTS_UNKNOWN
    restricted = codes & _RESTRICTED
    permissive = codes & _PERMISSIVE
    families = [
        name
        for name, present in (
            ("restricted", bool(restricted)),
            ("permissive", bool(permissive)),
            ("mit", mit),
            ("apache", apache),
            ("mpl", mpl),
            ("ogl", ogl),
            ("us", us_gov),
        )
        if present
    ]
    if len(families) != 1:
        return RIGHTS_UNKNOWN
    if restricted:
        if len(restricted) != 1:
            return RIGHTS_UNKNOWN
        return _RESTRICTED_TOKENS[next(iter(restricted))]
    if permissive:
        if permissive == {"by"}:
            return RIGHTS_CC_ATTRIBUTION
        if permissive <= _PERMISSIVE and permissive & {"by-sa", "zero"}:
            return RIGHTS_CREATIVE_COMMONS
        return RIGHTS_UNKNOWN
    if mit:
        return RIGHTS_MIT
    if apache:
        return RIGHTS_APACHE
    if mpl:
        return RIGHTS_MPL
    if ogl:
        return RIGHTS_UK_OGL
    if us_gov:
        return RIGHTS_US_GOVERNMENT_WORK
    return RIGHTS_UNKNOWN


def _text_codes(folded: str) -> set[str]:
    found: list[tuple[int, int, str]] = []
    for code, pattern in _TEXT_DEEDS:
        for match in pattern.finditer(folded):
            start, end = match.span()
            if any(start < prev_end and end > prev_start for prev_start, prev_end, _code in found):
                continue
            found.append((start, end, code))
    return {code for _start, _end, code in found}


def _url_codes(value: str) -> set[str]:
    found: set[str] = set()
    for code, pattern in _URL_DEEDS:
        if pattern.search(value):
            found.add(code)
    return found


def _states_us_government_work(page_html: str) -> bool:
    """True only when a rights metadata field says the item is a US government work."""

    visible = _without_hidden(page_html)
    fields = [content for key, content in _meta_pairs(visible) if key in _RIGHTS_META]
    for raw in fields:
        text = _plain(raw).casefold().translate(_DASHES)
        if not text or _NEGATED_US_GOV.search(text):
            continue
        if _US_GOV_WORK.search(text):
            return True
    return False


def _fold_licence_text(value: str) -> str:
    return _plain(_without_credit_regions(value)).casefold().translate(_DASHES)


def _wildcard_rules(text: str) -> list[tuple[str, str]]:
    groups: list[tuple[list[str], list[tuple[str, str]]]] = []
    agents: list[str] = []
    rules: list[tuple[str, str]] = []
    in_group = False
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip().casefold()
        value = value.strip()
        if key == "user-agent":
            if in_group and rules:
                groups.append((agents, rules))
                agents = []
                rules = []
            agents.append(value.casefold())
            in_group = True
        elif key in {"allow", "disallow"} and in_group:
            rules.append((key, value))
    if in_group:
        groups.append((agents, rules))
    for group_agents, group_rules in groups:
        if "*" in group_agents:
            return [(kind, prefix) for kind, prefix in group_rules if prefix.startswith("/")]
    return []


def _human_date(value: str) -> str | None:
    text = value.strip()
    month_first = re.fullmatch(r"([A-Za-zäöüÄÖÜ]+)\s+(\d{1,2}),\s+(\d{4})", text)
    if month_first:
        return _calendar_date(month_first.group(1), month_first.group(2), month_first.group(3))
    german = re.fullmatch(r"(\d{1,2})\.\s+([A-Za-zäöüÄÖÜ]+)\s+(\d{4})", text)
    if german:
        return _calendar_date(german.group(2), german.group(1), german.group(3))
    day_first = re.fullmatch(r"(\d{1,2})\s+([A-Za-zäöüÄÖÜ]+)\s+(\d{4})", text)
    if day_first:
        return _calendar_date(day_first.group(2), day_first.group(1), day_first.group(3))
    if _DATE.fullmatch(text):
        return _iso_day(text)
    return None


def _calendar_date(month_name: str, day_text: str, year_text: str) -> str | None:
    month = _MONTHS.get(month_name.casefold().rstrip("."))
    if month is None:
        return None
    try:
        return date(int(year_text), month, int(day_text)).isoformat()
    except ValueError:
        return None


def _iso_day(raw: object) -> str | None:
    if not isinstance(raw, str):
        return None
    match = _DATE_PREFIX.match(raw.strip())
    if match is None:
        return None
    value = match.group(1)
    try:
        date.fromisoformat(value)
    except ValueError:
        return None
    return value


def _sort_date(value: str) -> str:
    return "9999-99-99" if value == UNKNOWN_DATE else value


def _require_text(value: object, field: str, max_length: int) -> None:
    if not isinstance(value, str) or not value.strip() or value != value.strip():
        raise CatalogError(f"{field} is required")
    if len(value) > max_length or "<" in value or ">" in value or "\n" in value:
        raise CatalogError(f"{field} must be a short plain-text field")


def _reject_stored_body(value: object, path: str = "$") -> None:
    if isinstance(value, dict):
        found = _FORBIDDEN_KEYS.intersection(value)
        if found:
            names = ", ".join(sorted(found))
            raise CatalogError(f"{path} must not store page text ({names})")
        for key, item in value.items():
            _reject_stored_body(item, f"{path}.{key}")
        return
    if isinstance(value, list):
        for index, item in enumerate(value):
            _reject_stored_body(item, f"{path}[{index}]")


def _clean_title(value: str) -> str:
    text = _clean_text(value)
    lowered = text.casefold()
    for suffix in _SITE_SUFFIXES:
        if lowered.endswith(suffix) and len(text) > len(suffix):
            text = text[: -len(suffix)].strip()
            break
    return text


def _clean_text(value: str) -> str:
    text = unescape(_TAG.sub(" ", value)).replace("\xa0", " ")
    return re.sub(r"\s+", " ", text).strip()


def _plain(page_text: str) -> str:
    return _clean_text(page_text)


def _without_hidden(page_html: str) -> str:
    return _SCRIPT_STYLE.sub(" ", _COMMENT.sub(" ", page_html))


def _metas(page_html: str) -> dict[str, str]:
    found: dict[str, str] = {}
    for key, content in _meta_pairs(page_html):
        found.setdefault(key, content)
    return found


def _meta_pairs(page_html: str) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for tag in _META.findall(page_html):
        attrs = _attrs(tag)
        key = (attrs.get("property") or attrs.get("name") or "").lower()
        if key and attrs.get("content"):
            found.append((key, attrs["content"]))
    return found


def _is_generic_cc_licenses_url(href: str) -> bool:
    """True for the Creative Commons licences index, not a deed.

    http and https, a www host, a trailing slash, and a query string stay on
    that generic path. A deed such as /licenses/by/4.0/ does not.
    """

    if not isinstance(href, str) or not href.strip():
        return False
    parsed = urlparse(unescape(href).strip())
    if parsed.scheme.casefold() not in {"http", "https"}:
        return False
    host = (parsed.hostname or "").casefold().rstrip(".")
    if host not in _GENERIC_CC_HOSTS:
        return False
    path = (parsed.path or "").casefold()
    if len(path) > 1 and path.endswith("/"):
        path = path[:-1]
    return path == "/licenses"


def _without_generic_cc_license_anchors(page_html: str) -> str:
    """Drop anchors whose href is only the generic licences index.

    The visible text of that anchor is not a licence statement. Other text
    on the page is left in place.
    """

    def replace(match: re.Match[str]) -> str:
        href = _attrs("<a" + match.group(1) + ">").get("href", "")
        if _is_generic_cc_licenses_url(href):
            return " "
        return match.group(0)

    return _ANCHOR_ELEMENT.sub(replace, page_html)


def _without_credit_regions(page_html: str) -> str:
    """Drop a photo, image, or caption credit.

    A credit that names someone else's licence is not a licence for the page,
    including Photo credit: UNDRR, CC BY-NC-ND 2.0 and Photo: UNDRR,
    CC BY-NC-ND 2.0. Text after that credit stays.
    """

    def replace_block(match: re.Match[str]) -> str:
        attrs = match.group(2)
        body = match.group(3)
        if len(body) > 800:
            return match.group(0)
        if _CREDIT_CLASS.search(attrs) or _CREDIT_PHRASE.search(body) or _CREDIT_PHRASE.search(attrs):
            return " "
        return match.group(0)

    page_html = _CREDIT_BLOCK.sub(replace_block, page_html)
    parts: list[str] = []
    cursor = 0
    for match in _CREDIT_PHRASE.finditer(page_html):
        if match.start() < cursor:
            continue
        parts.append(page_html[cursor : match.start()])
        window = page_html[match.end() : match.end() + 500]
        parts.append(" ")
        cursor = match.end() + _credit_end(window)
    parts.append(page_html[cursor:])
    return "".join(parts)


def _credit_end(window: str) -> int:
    stops = [len(window)]
    sentence = _sentence_end(window)
    if sentence is not None:
        stops.append(sentence)
    boundary = _BLOCK_BOUNDARY.search(window)
    if boundary:
        stops.append(boundary.start())
    return min(stops)


def _sentence_end(window: str) -> int | None:
    in_tag = False
    for index, char in enumerate(window):
        if char == "<":
            in_tag = True
            continue
        if char == ">":
            in_tag = False
            continue
        if in_tag or char != ".":
            continue
        if index + 1 == len(window) or window[index + 1] in " \t\n\r<":
            return index + 1
    return None


def _hrefs(page_html: str) -> list[str]:
    found: list[str] = []
    for tag in _LINK.findall(page_html):
        href = _attrs(tag).get("href", "")
        if href:
            found.append(href)
    return found


def _attrs(tag: str) -> dict[str, str]:
    attrs: dict[str, str] = {}
    for name, double, single, bare in _ATTR.findall(tag):
        raw = double or single or bare
        attrs.setdefault(name.lower(), unescape(raw).strip())
    return attrs
